<?php

/**
 * Implements hook_preprocess_html().
 */
function nazpro_theme_preprocess_html(array &$variables) {
  // добавить класс к body
  $class = \Drupal::service('path.matcher')->isFrontPage() ? 'gl' : 'housing';
  $variables['attributes']['class'][] = $class;
}

function nazpro_theme_preprocess_page(&$variables) {
  // Подготавливаем представление для шапки (block_1)
  $variables['projects_header'] = views_embed_view('projects', 'block_1');

  // Подготавливаем представление для главной (block_2) - только для главной страницы
  if (\Drupal::service('path.matcher')->isFrontPage()) {
    $variables['projects_front'] = views_embed_view('projects', 'block_2');
  }

  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface/* && $node->bundle() === 'napravlenie'*/)
  {
    $variables['h1_title'] = $node->getTitle();
  }
}


function nazpro_theme_preprocess_views_view__projects__block_2(&$variables) {
  $view = $variables['view'];
  foreach ($view->result as $row) {
    $node = $row->_entity;
    $nid = $node->id();

    $count = \Drupal::entityQuery('node')
      ->condition('type', 'razdel_napravleniya')
      ->condition('field_napravlenie', $nid)
      ->count()
      ->accessCheck(TRUE)
      ->execute();

    $row->podrazdely_count = $count;
  }
}

function nazpro_theme_preprocess_node__razdel_napravleniya(&$variables) {

  //dump(array_keys($variables));
  //dump($variables['node']->toArray());
  //$variables['content_array'] = $variables['content'];
}

